### ISSUE TITLE
Mod causes item deleting and not spawning in properly.

### ISSUE THREAD

**Issue by DemonBunnyBon** [ds5678/Better-Water-Management#8]
With the mod installed it removes all of my clothing and I have to wear it every time I enter/exit an interior. It also removes all ammo from my current weapon. Additionally all items in the current map will spawn in one location (presumably 0,0,0). Some items are also lost (previously stored water, ammunition) I made sure that this mod was causing the issue (I removed this mod, nothing else, and everything worked properly again). Might be a compability issue with some other mods I'm not sure of that but removing this mod fixed the issue and I didn't try removing any other mods I used to check if it was a compability issue.

**Comment by ds5678** [comment]
Without a melonloader log file, I can't diagnose the problem

**Comment by MrSamsa** [comment]
I had just posted that I was having the same problem when I noticed that "Customsaveutilities" was not installed and is the cause for this problem.

Thanks for making this mod! 
Cheers.

**Comment by ds5678** [comment]
You're welcome!
